version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

jobs:
  post_create_environment:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry add --group doc mkdocs readthedocs mkdocs-material@^9.5.28 mkdocstrings@^0.25.1 mkdocstrings-python@^1.10.5


    post_install:
      - poetry install --only doc

